---
## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: vinanrra/7dtd-server
  tag: v0.4.4
  pullPolicy: IfNotPresent

imagePullSecrets: []

## Configure the deployment resource 
##
deployment:
  replicas: 1
  extraEnv: |
    - name: START_MODE
      value: "1"
    - name: VERSION
      value: "stable"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TimeZone
      value: "America/New_York"
    - name: TEST_ALERT
      value: "NO"
    - name: UPDATE_MODS
      value: "NO"
    - name: ALLOC_FIXES
      value: "NO"
    - name: ALLOC_FIXES_UPDATE
      value: "NO"
    - name: UNDEAD_LEGACY
      value: "NO"
    - name: UNDEAD_LEGACY_VERSION
      value: "stable"
    - name: UNDEAD_LEGACY_UPDATE
      value: "NO"
    - name: ENZOMBIES
      value: "NO"
    - name: ENZOMBIES_ADDON_SNUFKIN
      value: "NO"
    - name: ENZOMBIES_ADDON_ROBELOTO
      value: "NO"
    - name: ENZOMBIES_ADDON_NONUDES
      value: "NO"
    - name: ENZOMBIES_UPDATE
      value: "NO"
    - name: CPM
      value: "NO"
    - name: CPM_UPDATE
      value: "NO"
    - name: BEPINEX
      value: "NO"
    - name: BEPINEX_UPDATE
      value: "NO"
    - name: BACKUP
      value: "YES"
    - name: MONITOR
      value: "NO"
    
## Expose the 7dtd service and
## Provides options for the service so chart users have the full choice
## Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort

## Set the LoadBalancer service type to internal only.
## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
##
# loadBalancerIP:

## Load Balancer sources
## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
##
# loadBalancerSourceRanges:
# - 10.10.10.0/24

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

## Configure liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
#readinessProbe:
#  httpGet:
#    path: /
#    port: 7dtd-webadmin
#  initialDelaySeconds: 60
#  periodSeconds: 15
#  timeoutSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 7dtd-webadmin
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi